---
ansible_ssh_user: root
ansible_ssh_port: 22
ansible_ssh_password: "pass"
# ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_become: false
ansible_sudo_user: root
ansible_become_method: sudo
# gather_facts: false


